### ISSUE TITLE
Register form.

### ISSUE THREAD

**Issue by Dramatocles** [JaysonHayson/Single_Page_Application#10]
Registrierungs Funktion reagiert noch nicht auf abgeschlossenen prozess.
Beim drücken des knopfes wird die datenbank befüllt, die form bleibt jedoch unverändert und der User weiss nicht ob es erfolgreich war oder nicht.

- [x] User Feedback - Success/Failure.
- [x] User Feedback - Grober grund des fails -> z.b. Username bereits in verwendung. 
- [x] Leeren des forms nach erfolg, evtl zurückleitung zum login.

**Comment by JaysonHayson** [comment]
Thank you <3
