### ISSUE TITLE
FRONTEND DEVELOPMENT

### ISSUE THREAD

**Issue by JaysonHayson** [JaysonHayson/Single_Page_Application#6]
- [x]  Design and implement the categories and products UI.
- [x]  Develop the user registration and login forms.
- [x]  Create the shopping cart UI and functionality.
- [x]  Ensure the app is responsive.

- [x] #10

**Comment by Dramatocles** [comment]
- [ ] Register form user feedback.

**Comment by JaysonHayson** [comment]
<3
